Revert "Update constraints in  java build files / Constrain lib in UI (#1060)"
The is causing indexing failures due to missing libraries:

```
Exception in thread “main” java.lang.NoClassDefFoundError:
ch/qos/logback/classic/Level
```

Removing the exclusion from indexing/ fails at a different location
processing DataFlow results so just rolling back the entire change for
now.

This reverts commit fdbc5b3af00551ac9ced03be3ae2d21bce3f5d8d.